/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author ellis_000
 */
public class GUImain extends javax.swing.JFrame {


    
    
    
    /**
     * Creates new form GUImain
     */
    
    DefaultTableModel model;
    DefaultTableModel custModel;
    public GUImain() {
        initComponents();
        model = (DefaultTableModel)tblOrderlist.getModel();
        custModel = (DefaultTableModel)tblCustomerlist.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JobTypeButtonGroup = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JTabbedPane();
        pnlCustomerlist = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomerlist = new javax.swing.JTable();
        btnRefreshcustomerlist = new javax.swing.JButton();
        btnSendemailcustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDeletecustomerlist = new javax.swing.JButton();
        pnlOrderlist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderlist = new javax.swing.JTable();
        btnRefreshorderlist = new javax.swing.JButton();
        btnDeleteorderlist = new javax.swing.JButton();
        btnSendemailorderlist = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnlInventory = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnRefreshinventory = new javax.swing.JButton();
        btnSaveinventory = new javax.swing.JButton();
        btnSendemailinvetory = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlEmployee = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnRefreshemply = new javax.swing.JButton();
        btnSaveemployee = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pnlCreateorder = new javax.swing.JPanel();
        lblCustomernumber = new javax.swing.JLabel();
        lblInventorynumber = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblCustomerrequest = new javax.swing.JLabel();
        lblJobtype = new javax.swing.JLabel();
        lblDeposit = new javax.swing.JLabel();
        lblPriceeach = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblEmployeenumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCustomerrequest = new javax.swing.JTextArea();
        lblBalanceoutput = new javax.swing.JLabel();
        txtDeposit = new javax.swing.JTextField();
        txtPriceeach = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtInventorynumber = new javax.swing.JTextField();
        txtCustomernumber = new javax.swing.JTextField();
        txtEmployeenumber = new javax.swing.JTextField();
        lblTotaloutput = new javax.swing.JLabel();
        btnCreateorder = new javax.swing.JButton();
        rdoPrint = new javax.swing.JRadioButton();
        rdoEngrave = new javax.swing.JRadioButton();
        btnClearordr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        totalPrice = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        balance = new javax.swing.JTextPane();
        btntotBalance = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnOrdersave = new javax.swing.JButton();
        pnlAddcustomer = new javax.swing.JPanel();
        lblCustomername = new javax.swing.JLabel();
        lblPhonenumber = new javax.swing.JLabel();
        lblStreetaddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnCreatenewcustomer = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtZipcode = new javax.swing.JTextField();
        txtCustomername = new javax.swing.JTextField();
        txtPhonenumber = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtStreetaddress = new javax.swing.JTextField();
        lblWarning = new javax.swing.JLabel();
        btnClearcust = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSavecustomerlist = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCustomerlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone", "Address", "City", "State", "Zip", "Email"
            }
        ));
        jScrollPane3.setViewportView(tblCustomerlist);

        btnRefreshcustomerlist.setText("Refresh");
        btnRefreshcustomerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshcustomerlistActionPerformed(evt);
            }
        });

        btnSendemailcustomer.setText("Send Email to Customer");
        btnSendemailcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendemailcustomerActionPerformed(evt);
            }
        });

        jLabel2.setText("*Double click on field to edit");

        btnDeletecustomerlist.setText("Delete");
        btnDeletecustomerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletecustomerlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomerlistLayout = new javax.swing.GroupLayout(pnlCustomerlist);
        pnlCustomerlist.setLayout(pnlCustomerlistLayout);
        pnlCustomerlistLayout.setHorizontalGroup(
            pnlCustomerlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerlistLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlCustomerlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendemailcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCustomerlistLayout.createSequentialGroup()
                        .addComponent(btnDeletecustomerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshcustomerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(pnlCustomerlistLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCustomerlistLayout.setVerticalGroup(
            pnlCustomerlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnlCustomerlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletecustomerlist)
                    .addComponent(btnRefreshcustomerlist))
                .addGap(18, 18, 18)
                .addComponent(btnSendemailcustomer)
                .addGap(26, 26, 26))
        );

        pnlMain.addTab("Customer List", pnlCustomerlist);

        tblOrderlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee #", "Customer #", "Job Type", "Inventory #", "Quantity", "Price Each", "Balance", "Customer Notes"
            }
        ));
        jScrollPane2.setViewportView(tblOrderlist);

        btnRefreshorderlist.setText("Refresh");
        btnRefreshorderlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshorderlistActionPerformed(evt);
            }
        });

        btnDeleteorderlist.setText("Delete");
        btnDeleteorderlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteorderlistActionPerformed(evt);
            }
        });

        btnSendemailorderlist.setText("Send Email");
        btnSendemailorderlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendemailorderlistActionPerformed(evt);
            }
        });

        jLabel9.setText("*Double click on field to edit");

        javax.swing.GroupLayout pnlOrderlistLayout = new javax.swing.GroupLayout(pnlOrderlist);
        pnlOrderlist.setLayout(pnlOrderlistLayout);
        pnlOrderlistLayout.setHorizontalGroup(
            pnlOrderlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderlistLayout.createSequentialGroup()
                        .addComponent(btnDeleteorderlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                        .addComponent(btnRefreshorderlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSendemailorderlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOrderlistLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOrderlistLayout.setVerticalGroup(
            pnlOrderlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addGap(24, 24, 24)
                .addGroup(pnlOrderlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteorderlist)
                    .addComponent(btnRefreshorderlist))
                .addGap(18, 18, 18)
                .addComponent(btnSendemailorderlist)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlMain.addTab("Order List", pnlOrderlist);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, null, null, null, null},
                {"", "", "", null, null, null, null, null},
                {"", "", "", null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inv ID", "Quantity", "On Order", "# Sold", "Inv Name", "Inv Price", "Manufatured By", "Description"
            }
        ));
        jScrollPane4.setViewportView(tblInventory);

        btnRefreshinventory.setText("Refresh");
        btnRefreshinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshinventoryActionPerformed(evt);
            }
        });

        btnSaveinventory.setText("Save");
        btnSaveinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveinventoryActionPerformed(evt);
            }
        });

        btnSendemailinvetory.setText("Send Request");
        btnSendemailinvetory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendemailinvetoryActionPerformed(evt);
            }
        });

        jLabel4.setText("*Double click on field to edit");

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendemailinvetory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(btnSaveinventory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshinventory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveinventory)
                    .addComponent(btnRefreshinventory))
                .addGap(18, 18, 18)
                .addComponent(btnSendemailinvetory)
                .addGap(28, 28, 28))
        );

        pnlMain.addTab("Inventory", pnlInventory);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Phone"
            }
        ));
        jScrollPane7.setViewportView(tblEmployee);

        btnRefreshemply.setText("Refresh");
        btnRefreshemply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshemplyActionPerformed(evt);
            }
        });

        btnSaveemployee.setText("Save");
        btnSaveemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveemployeeActionPerformed(evt);
            }
        });

        jLabel11.setText("*Double click on field to edit");

        javax.swing.GroupLayout pnlEmployeeLayout = new javax.swing.GroupLayout(pnlEmployee);
        pnlEmployee.setLayout(pnlEmployeeLayout);
        pnlEmployeeLayout.setHorizontalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmployeeLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlEmployeeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                                .addComponent(btnSaveemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefreshemply, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))))
        );
        pnlEmployeeLayout.setVerticalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveemployee)
                    .addComponent(btnRefreshemply))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnlMain.addTab("Employee", pnlEmployee);

        lblCustomernumber.setText("Customer Number: ");

        lblInventorynumber.setText("Inventory Number:");

        lblQuantity.setText("Quantity:");

        lblCustomerrequest.setText("Customer Request:");

        lblJobtype.setText("Job Type:");

        lblDeposit.setText("Deposit:");

        lblPriceeach.setText("Price each:");

        lblTotal.setText("Total:");

        lblBalance.setText("Balance:");

        lblEmployeenumber.setText("Employee Number:");

        txtCustomerrequest.setColumns(20);
        txtCustomerrequest.setRows(5);
        jScrollPane1.setViewportView(txtCustomerrequest);
        txtCustomerrequest.getAccessibleContext().setAccessibleParent(pnlCreateorder);

        txtInventorynumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInventorynumberActionPerformed(evt);
            }
        });

        btnCreateorder.setText("Create Order");
        btnCreateorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateorderActionPerformed(evt);
            }
        });

        JobTypeButtonGroup.add(rdoPrint);
        rdoPrint.setText("Print");

        JobTypeButtonGroup.add(rdoEngrave);
        rdoEngrave.setText("Engrave");
        rdoEngrave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoEngraveActionPerformed(evt);
            }
        });

        btnClearordr.setText("Clear");
        btnClearordr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearordrActionPerformed(evt);
            }
        });

        jLabel1.setText("$");

        totalPrice.setEditable(false);
        jScrollPane5.setViewportView(totalPrice);
        totalPrice.getAccessibleContext().setAccessibleName("totalPrice");
        totalPrice.getAccessibleContext().setAccessibleParent(pnlCreateorder);

        balance.setEditable(false);
        jScrollPane6.setViewportView(balance);
        balance.getAccessibleContext().setAccessibleParent(pnlCreateorder);

        btntotBalance.setText("Calculate Totals");
        btntotBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotBalanceActionPerformed(evt);
            }
        });

        jLabel6.setText("$");

        jLabel7.setText("$");

        jLabel8.setText("$");

        btnOrdersave.setText("Save");
        btnOrdersave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateorderLayout = new javax.swing.GroupLayout(pnlCreateorder);
        pnlCreateorder.setLayout(pnlCreateorderLayout);
        pnlCreateorderLayout.setHorizontalGroup(
            pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateorderLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInventorynumber)
                            .addComponent(lblJobtype))
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdoPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoEngrave)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtInventorynumber))))
                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCreateorderLayout.createSequentialGroup()
                                        .addComponent(lblCustomerrequest)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                                .addComponent(lblPriceeach)
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel1))
                                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                                .addComponent(lblTotal)
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabel6))
                                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                                .addComponent(lblDeposit)
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel7))
                                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                                .addComponent(lblBalance)
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel8)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addComponent(lblQuantity)
                                .addGap(58, 58, 58)))
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity)
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addComponent(btnClearordr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOrdersave)
                                .addGap(18, 18, 18)
                                .addComponent(btntotBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCreateorder))
                            .addComponent(txtPriceeach, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBalanceoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotaloutput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 327, Short.MAX_VALUE))
                            .addComponent(txtDeposit)
                            .addComponent(jScrollPane1)))
                    .addGroup(pnlCreateorderLayout.createSequentialGroup()
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomernumber)
                            .addComponent(lblEmployeenumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployeenumber)
                            .addComponent(txtCustomernumber))))
                .addGap(24, 24, 24))
        );
        pnlCreateorderLayout.setVerticalGroup(
            pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateorderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeenumber)
                    .addComponent(txtEmployeenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomernumber)
                    .addComponent(txtCustomernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobtype)
                    .addComponent(rdoPrint)
                    .addComponent(rdoEngrave))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInventorynumber)
                    .addComponent(txtInventorynumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceeach)
                    .addComponent(txtPriceeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal)
                        .addComponent(lblTotaloutput)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeposit)
                    .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBalance)
                        .addComponent(lblBalanceoutput)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerrequest)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCreateorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateorder)
                    .addComponent(btnClearordr)
                    .addComponent(btntotBalance)
                    .addComponent(btnOrdersave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain.addTab("Create Order", pnlCreateorder);

        pnlAddcustomer.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlAddcustomerComponentRemoved(evt);
            }
        });

        lblCustomername.setText("Customer Name:");

        lblPhonenumber.setText("Phone Number:");

        lblStreetaddress.setText("Street Address:");

        lblCity.setText("City:");

        lblState.setText("State:");

        lblZipcode.setText("Zip Code:");

        lblEmail.setText("E-Mail:");

        btnCreatenewcustomer.setText("Create New Customer");
        btnCreatenewcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatenewcustomerActionPerformed(evt);
            }
        });

        txtCustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomernameActionPerformed(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(204, 0, 0));
        lblWarning.setText("*Please Check to see if the customer is already an established customer before creating a New Customer Account");

        btnClearcust.setText("Clear");
        btnClearcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearcustActionPerformed(evt);
            }
        });

        jLabel5.setText("Customer ID #");

        btnSavecustomerlist.setText("Save");
        btnSavecustomerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavecustomerlistActionPerformed(evt);
            }
        });

        jLabel10.setText("*Customer ID is automatically generated");

        javax.swing.GroupLayout pnlAddcustomerLayout = new javax.swing.GroupLayout(pnlAddcustomer);
        pnlAddcustomer.setLayout(pnlAddcustomerLayout);
        pnlAddcustomerLayout.setHorizontalGroup(
            pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblZipcode)
                                .addGap(72, 72, 72)
                                .addComponent(txtZipcode))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblPhonenumber)
                                .addGap(44, 44, 44)
                                .addComponent(txtPhonenumber))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblState)
                                .addGap(88, 88, 88)
                                .addComponent(txtState))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblStreetaddress)
                                .addGap(42, 42, 42)
                                .addComponent(txtStreetaddress))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblCity)
                                .addGap(95, 95, 95)
                                .addComponent(txtCity))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCustomername)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomername)
                                    .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(86, 86, 86)
                                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                                        .addComponent(btnClearcust)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSavecustomerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(btnCreatenewcustomer))
                                    .addComponent(txtEmail)))))
                    .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAddcustomerLayout.setVerticalGroup(
            pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddcustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomername)
                    .addComponent(txtCustomername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhonenumber)
                    .addComponent(txtPhonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStreetaddress)
                    .addComponent(txtStreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(pnlAddcustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatenewcustomer)
                    .addComponent(btnClearcust)
                    .addComponent(btnSavecustomerlist))
                .addContainerGap())
        );

        pnlMain.addTab("Add Customer", pnlAddcustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAddcustomerComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlAddcustomerComponentRemoved
        // VOIDDDDDDDDDDDDDDDDDDDD design Error
    }//GEN-LAST:event_pnlAddcustomerComponentRemoved

    //clear button for adding new customer
    private void btnClearcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearcustActionPerformed
      
      txtCustomername.setText(null);
      txtPhonenumber.setText(null);
      txtStreetaddress.setText(null);
      txtCity.setText(null);
      txtState.setText(null);
      txtZipcode.setText(null);
      txtEmail.setText(null);
    }//GEN-LAST:event_btnClearcustActionPerformed

    //button adds all customer information to the customer table
    private void btnCreatenewcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatenewcustomerActionPerformed
        int custPhone, custZip;
        String custName, custAddr, custCity, custState, custEmail;
        
       
        custPhone = Integer.parseInt(txtPhonenumber.getText());
        custZip = Integer.parseInt(txtZipcode.getText());
        custName = txtCustomername.getText();
        custAddr = txtStreetaddress.getText();
        custCity = txtCity.getText();
        custState = txtState.getText();
        custEmail = txtEmail.getText();
        
        custModel.insertRow(custModel.getRowCount(), new Object[]{ custName, custPhone,
        custAddr, custCity, custState, custZip, custEmail});
        
    }//GEN-LAST:event_btnCreatenewcustomerActionPerformed

    //clear button for adding order
    private void btnClearordrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearordrActionPerformed
        txtEmployeenumber.setText(null);
        txtCustomernumber.setText(null);
        txtInventorynumber.setText(null);
        txtQuantity.setText(null);
        txtPriceeach.setText(null);
        txtDeposit.setText(null);
        txtCustomerrequest.setText(null);
        JobTypeButtonGroup.clearSelection();
        totalPrice.setText(null);
        balance.setText(null);
        
        
        
    }//GEN-LAST:event_btnClearordrActionPerformed

    private void txtCustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomernameActionPerformed

    //button adds all order information to the order table
    private void btnCreateorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateorderActionPerformed
        float price, deposit, custTotal, custBalance;
        String custRequest, jobType;
        int emplNumb, custNumb, invNumb, invQnty;
        
        if(rdoPrint.isSelected()){
            jobType = "Engrave"; }else {jobType = "Print"; }
        
        emplNumb = Integer.parseInt(txtEmployeenumber.getText());
        custNumb = Integer.parseInt(txtCustomernumber.getText());
        invNumb = Integer.parseInt(txtInventorynumber.getText());
        invQnty = Integer.parseInt(txtQuantity.getText());
        price = Float.parseFloat(txtPriceeach.getText());
        deposit = Float.parseFloat(txtDeposit.getText());
        custTotal = invQnty * price;
        custBalance = custTotal - deposit;
        custRequest = txtCustomerrequest.getText();
        
       
        
        model.insertRow(model.getRowCount(), new Object[]{emplNumb,custNumb, jobType,
        invNumb, invQnty, price, custBalance, custRequest});
        
        
    }//GEN-LAST:event_btnCreateorderActionPerformed

    
    private void txtInventorynumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInventorynumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventorynumberActionPerformed

    //tallies and shows the total cost pre deposit and post deposit from the create order screen
    private void btntotBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotBalanceActionPerformed
        float custTotal, custBalance, invQnty, price, deposit;
        invQnty = Integer.parseInt(txtQuantity.getText());
        price = Float.parseFloat(txtPriceeach.getText());
        deposit = Float.parseFloat(txtDeposit.getText());
        
        custTotal = invQnty * price;
        custBalance = custTotal - deposit;
        totalPrice.setText("" + custTotal);
        balance.setText("" + custBalance);
    }//GEN-LAST:event_btntotBalanceActionPerformed

    //button sends an email to the customer about their order
    private void btnSendemailcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendemailcustomerActionPerformed
       JOptionPane.showMessageDialog(null, "Email sent to customer!");
    }//GEN-LAST:event_btnSendemailcustomerActionPerformed

    //button to save the inventory information to the database
    private void btnSaveinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveinventoryActionPerformed
        JOptionPane.showMessageDialog(null, "Saved to database!");
    }//GEN-LAST:event_btnSaveinventoryActionPerformed

    //button to email the warehouse for item availability
    private void btnSendemailinvetoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendemailinvetoryActionPerformed
        JOptionPane.showMessageDialog(null, "Request sent to warehouse!");
    }//GEN-LAST:event_btnSendemailinvetoryActionPerformed

    //button to refresh the inventory table
    private void btnRefreshinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshinventoryActionPerformed
                                                             
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            String sql = "SELECT * FROM INVENTORY";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblInventory.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_btnRefreshinventoryActionPerformed

    //button to refresh/clear the order list
    private void btnRefreshorderlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshorderlistActionPerformed
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            String sql = "SELECT * FROM ORDERS";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblOrderlist.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnRefreshorderlistActionPerformed

    //button to save the order information to the order list
    private void btnDeleteorderlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteorderlistActionPerformed
          int row = tblOrderlist.getSelectedRow();
        String cell = tblOrderlist.getModel().getValueAt(row,0).toString();
        String sql = "DELETE FROM ORDERS WHERE ORDID =" + cell;

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Deleted Selection.");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_btnDeleteorderlistActionPerformed

    //button to send an email to management for order validation
    private void btnSendemailorderlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendemailorderlistActionPerformed
        JOptionPane.showMessageDialog(null, "Email sent to manager for validation!");
    }//GEN-LAST:event_btnSendemailorderlistActionPerformed

    private void btnSavecustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavecustomerlistActionPerformed
          try {
              PreparedStatement pst; 
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        Connection conect = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
       String sql = "INSERT INTO CUSTOMER(CUSTNAME, CUSTPHONE, CUSTADDRS, CUSTCITY, CUSTSTATE, CUSTZIP, CUSTEMAIL)values(?,?,?,?,?,?,?)";
       
       pst = conect.prepareStatement(sql);
       pst.setString(1, txtCustomername.getText());
       pst.setString(2, txtPhonenumber.getText());
       pst.setString(3, txtStreetaddress.getText());
       pst.setString(4, txtCity.getText());
       pst.setString(5, txtState.getText());
       pst.setString(6, txtZipcode.getText());
       pst.setString(7, txtEmail.getText());
       
       pst.executeUpdate();
       JOptionPane.showMessageDialog(null, "Saved to database!");
       } catch (Exception e){
        
        JOptionPane.showMessageDialog(null, e);
       }

    }//GEN-LAST:event_btnSavecustomerlistActionPerformed

    //button to refresh the customer table
    private void btnRefreshcustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshcustomerlistActionPerformed
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            String sql = "SELECT * FROM CUSTOMER";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblCustomerlist.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_btnRefreshcustomerlistActionPerformed

    private void btnDeletecustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletecustomerlistActionPerformed
        
         int row = tblCustomerlist.getSelectedRow();
        String cell = tblCustomerlist.getModel().getValueAt(row,0).toString();
        String sql = "DELETE FROM CUSTOMER WHERE CUSTID =" + cell;

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Deleted Selection.");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_btnDeletecustomerlistActionPerformed

    private void btnRefreshemplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshemplyActionPerformed
              try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://c:/zzcis470/seniorproject/SPDBv2.accdb","","");
            String sql = "SELECT * FROM EMPLOYEE";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblEmployee.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnRefreshemplyActionPerformed

    private void btnSaveemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveemployeeActionPerformed
         JOptionPane.showMessageDialog(null, "Saved to database!");
    }//GEN-LAST:event_btnSaveemployeeActionPerformed

    private void btnOrdersaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersaveActionPerformed
     
         JOptionPane.showMessageDialog(null, "Saved to database!");
    }//GEN-LAST:event_btnOrdersaveActionPerformed

    private void rdoEngraveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoEngraveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoEngraveActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUImain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JobTypeButtonGroup;
    private javax.swing.JTextPane balance;
    private javax.swing.JButton btnClearcust;
    private javax.swing.JButton btnClearordr;
    private javax.swing.JButton btnCreatenewcustomer;
    private javax.swing.JButton btnCreateorder;
    private javax.swing.JButton btnDeletecustomerlist;
    private javax.swing.JButton btnDeleteorderlist;
    private javax.swing.JButton btnOrdersave;
    private javax.swing.JButton btnRefreshcustomerlist;
    private javax.swing.JButton btnRefreshemply;
    private javax.swing.JButton btnRefreshinventory;
    private javax.swing.JButton btnRefreshorderlist;
    private javax.swing.JButton btnSavecustomerlist;
    private javax.swing.JButton btnSaveemployee;
    private javax.swing.JButton btnSaveinventory;
    private javax.swing.JButton btnSendemailcustomer;
    private javax.swing.JButton btnSendemailinvetory;
    private javax.swing.JButton btnSendemailorderlist;
    private javax.swing.JButton btntotBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceoutput;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCustomername;
    private javax.swing.JLabel lblCustomernumber;
    private javax.swing.JLabel lblCustomerrequest;
    private javax.swing.JLabel lblDeposit;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeenumber;
    private javax.swing.JLabel lblInventorynumber;
    private javax.swing.JLabel lblJobtype;
    private javax.swing.JLabel lblPhonenumber;
    private javax.swing.JLabel lblPriceeach;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetaddress;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotaloutput;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JPanel pnlAddcustomer;
    private javax.swing.JPanel pnlCreateorder;
    private javax.swing.JPanel pnlCustomerlist;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JTabbedPane pnlMain;
    private javax.swing.JPanel pnlOrderlist;
    private javax.swing.JRadioButton rdoEngrave;
    private javax.swing.JRadioButton rdoPrint;
    private javax.swing.JTable tblCustomerlist;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblOrderlist;
    private javax.swing.JTextPane totalPrice;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCustomername;
    private javax.swing.JTextField txtCustomernumber;
    private javax.swing.JTextArea txtCustomerrequest;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeenumber;
    private javax.swing.JTextField txtInventorynumber;
    private javax.swing.JTextField txtPhonenumber;
    private javax.swing.JTextField txtPriceeach;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetaddress;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
